# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiAES.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from asyncio.windows_events import NULL
from email.utils import parseaddr
from pickle import FALSE, TRUE
from tabnanny import check
from unittest.mock import patch
from PyQt5 import QtCore, QtGui, QtWidgets
import main
from PyQt5.QtWidgets import QMessageBox, QFileDialog
import binascii


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 758)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 41, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.EncryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.EncryptButton.setGeometry(QtCore.QRect(520, 40, 93, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.EncryptButton.setFont(font)
        self.EncryptButton.setObjectName("EncryptButton")
        self.DecryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.DecryptButton.setGeometry(QtCore.QRect(520, 97, 93, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.DecryptButton.setFont(font)
        self.DecryptButton.setObjectName("DecryptButton")
        self.IOtext = QtWidgets.QTextEdit(self.centralwidget)
        self.IOtext.setGeometry(QtCore.QRect(90, 40, 411, 87))
        self.IOtext.setObjectName("IOtext")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.PassText = QtWidgets.QLineEdit(self.centralwidget)
        self.PassText.setGeometry(QtCore.QRect(130, 150, 151, 22))
        self.PassText.setObjectName("PassText")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.PathFileText = QtWidgets.QLineEdit(self.centralwidget)
        self.PathFileText.setGeometry(QtCore.QRect(90, 201, 411, 31))
        self.PathFileText.setObjectName("PathFileText")
        self.BrowseFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseFileButton.setGeometry(QtCore.QRect(520, 200, 93, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.BrowseFileButton.setFont(font)
        self.BrowseFileButton.setObjectName("BrowseFileButton")
        self.EncryptFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.EncryptFileButton.setGeometry(QtCore.QRect(140, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.EncryptFileButton.setFont(font)
        self.EncryptFileButton.setObjectName("EncryptFileButton")
        self.DecryptFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.DecryptFileButton.setGeometry(QtCore.QRect(390, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.DecryptFileButton.setFont(font)
        self.DecryptFileButton.setObjectName("DecryptFileButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 250, 51, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.PathOutputText = QtWidgets.QLineEdit(self.centralwidget)
        self.PathOutputText.setGeometry(QtCore.QRect(90, 250, 411, 31))
        self.PathOutputText.setObjectName("PathOutputText")
        self.BrowseOutputFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseOutputFileButton.setGeometry(QtCore.QRect(520, 250, 93, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.BrowseOutputFileButton.setFont(font)
        self.BrowseOutputFileButton.setObjectName("BrowseOutputFileButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 631, 351))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.groupBox.setObjectName("groupBox")
        self.ClearButton = QtWidgets.QPushButton(self.groupBox)
        self.ClearButton.setGeometry(QtCore.QRect(420, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ClearButton.setFont(font)
        self.ClearButton.setObjectName("ClearButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 360, 631, 371))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.CreateKeyRSA = QtWidgets.QPushButton(self.groupBox_2)
        self.CreateKeyRSA.setGeometry(QtCore.QRect(230, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CreateKeyRSA.setFont(font)
        self.CreateKeyRSA.setObjectName("CreateKeyRSA")
        self.PathCreateKeyRSA = QtWidgets.QLineEdit(self.groupBox_2)
        self.PathCreateKeyRSA.setEnabled(True)
        self.PathCreateKeyRSA.setGeometry(QtCore.QRect(80, 60, 411, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PathCreateKeyRSA.setFont(font)
        self.PathCreateKeyRSA.setStyleSheet("")
        self.PathCreateKeyRSA.setObjectName("PathCreateKeyRSA")
        self.BrowseCreateKeyButton = QtWidgets.QPushButton(self.groupBox_2)
        self.BrowseCreateKeyButton.setGeometry(QtCore.QRect(510, 60, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BrowseCreateKeyButton.setFont(font)
        self.BrowseCreateKeyButton.setObjectName("BrowseCreateKeyButton")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 51, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBoxXuatKey = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxXuatKey.setGeometry(QtCore.QRect(370, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBoxXuatKey.setFont(font)
        self.checkBoxXuatKey.setObjectName("checkBoxXuatKey")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.BrowseInputKeyRSA = QtWidgets.QPushButton(self.groupBox_2)
        self.BrowseInputKeyRSA.setGeometry(QtCore.QRect(510, 160, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BrowseInputKeyRSA.setFont(font)
        self.BrowseInputKeyRSA.setObjectName("BrowseInputKeyRSA")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(130, 220, 351, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("selection-background-color: rgb(85, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.InputPlaintextRSA = QtWidgets.QTextEdit(self.groupBox_2)
        self.InputPlaintextRSA.setGeometry(QtCore.QRect(80, 270, 411, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.InputPlaintextRSA.setFont(font)
        self.InputPlaintextRSA.setObjectName("InputPlaintextRSA")
        self.EncryptFileButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.EncryptFileButton_2.setGeometry(QtCore.QRect(500, 270, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.EncryptFileButton_2.setFont(font)
        self.EncryptFileButton_2.setObjectName("EncryptFileButton_2")
        self.DecryptFileButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.DecryptFileButton_2.setGeometry(QtCore.QRect(500, 330, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DecryptFileButton_2.setFont(font)
        self.DecryptFileButton_2.setObjectName("DecryptFileButton_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.InputKeyPath = QtWidgets.QLineEdit(self.groupBox_2)
        self.InputKeyPath.setEnabled(True)
        self.InputKeyPath.setGeometry(QtCore.QRect(80, 160, 411, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.InputKeyPath.setFont(font)
        self.InputKeyPath.setStyleSheet("")
        self.InputKeyPath.setObjectName("InputKeyPath")
        self.CreateKeyRSA.raise_()
        self.BrowseCreateKeyButton.raise_()
        self.label_5.raise_()
        self.checkBoxXuatKey.raise_()
        self.label_6.raise_()
        self.BrowseInputKeyRSA.raise_()
        self.label_7.raise_()
        self.InputPlaintextRSA.raise_()
        self.EncryptFileButton_2.raise_()
        self.DecryptFileButton_2.raise_()
        self.PathCreateKeyRSA.raise_()
        self.comboBox_2.raise_()
        self.InputKeyPath.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.EncryptButton.raise_()
        self.DecryptButton.raise_()
        self.IOtext.raise_()
        self.label_2.raise_()
        self.PassText.raise_()
        self.label_3.raise_()
        self.PathFileText.raise_()
        self.BrowseFileButton.raise_()
        self.EncryptFileButton.raise_()
        self.DecryptFileButton.raise_()
        self.label_4.raise_()
        self.PathOutputText.raise_()
        self.BrowseOutputFileButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #connect
        self.EncryptButton.clicked.connect(self.Encrypt)
        self.DecryptButton.clicked.connect(self.DeCrypt)
        self.BrowseFileButton.clicked.connect(self.BrowseFile)
        self.BrowseOutputFileButton.clicked.connect(self.BrowseOutput)
        self.EncryptFileButton.clicked.connect(self.CheckFileInput_Encrypt)
        self.DecryptFileButton.clicked.connect(self.CheckFileInput_Decrypt)
        self.ClearButton.clicked.connect(self.Clear)
        self.BrowseCreateKeyButton.clicked.connect(self.Path_Output_Key)
        self.CreateKeyRSA.clicked.connect(self.CreateKey_RSA)
        self.BrowseInputKeyRSA.clicked.connect(self.Browse_Key)
        self.EncryptFileButton_2.clicked.connect(self.EncryptRSA)
        self.DecryptFileButton_2.clicked.connect(self.DecryptRSA)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #Ham connect
    def Browse_Key(self):
        try:
            f = "PEM File (*.PEM);; DER File (*.DER);; All File (*)"
            df_foler = 'C:\\'
            fname = QFileDialog.getOpenFileName(None, 'Lựa chọn File', df_foler, f)
        except:
            pass
        self.InputKeyPath.setText(fname[0])

    def CreateKey_RSA(self):
        try:
            if (self.PathCreateKeyRSA.text() == ""):
                pass
            else:
                check = 1
                if self.checkBoxXuatKey.checkState() == 0:
                    check == 0
                sizeK = int(self.comboBox_2.currentText())
                main.CreatKeyRSA(self.PathCreateKeyRSA.text(), check, sizeK)
        except:
            self.show_Error_InputFile
            self.PathCreateKeyRSA.clear()

    def Path_Output_Key(self):
        try:
            folder = "C:\\"
            fname = QFileDialog.getExistingDirectory(None, "Chọn đường dẫn", folder)
        except:
            pass
        self.PathCreateKeyRSA.setText(fname)

    def show_Error_Input_Empty(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error Input")
        msg.setText("Chưa nhập Pass")
        x = msg.exec_()

    def show_Error_Input_Key_RSA(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error Input")
        msg.setText("Chưa nhập Key")
        x = msg.exec_()
    
    def show_Error_Long_Input(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error Input")
        msg.setText("Pass quá dài")
        x = msg.exec_()

    def show_Error_Wrong_Input(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error Input")
        msg.setText("Error Pass")
        x = msg.exec_()

    def show_Error_InputFile(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Input Error")
        x = msg.exec_()

    def show_Error_OutputFile(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Onput Error")
        x = msg.exec_()

    def Clear(self):
        self.IOtext.clear()
        self.PassText.clear()
        self.PathFileText.clear()
        self.PathOutputText.clear()
        self.PathCreateKeyRSA.clear()
        self.InputKeyPath.clear()
        self.InputPlaintextRSA.clear()

    def BrowseFile(self):
        try:
            f = "Text File (*.txt);; PDF File (*.pdf);; Encrypted File (*.enc);;All File (*)"
            df_foler = 'C:\\'
            fname = QFileDialog.getOpenFileNames(None, 'Lựa chọn File', df_foler, f)
        except:
            pass
        self.PathFileText.clear()
        str1 = fname[0]
        str1 = '*'.join(str1)
        self.PathFileText.setText(str1)
    
    def BrowseOutput(self):
        try:
            folder = "C:\\"
            fname = QFileDialog.getExistingDirectory(None, "Chọn đường dẫn", folder)
        except:
            pass
        
        self.PathOutputText.clear()
        self.PathOutputText.setText(fname)

    def CheckFileInput_Encrypt(self):
            if self.PathFileText.text() != "":
                self.EncryptFile()
            elif self.PathFileText.text() == "":
                pass

    def CheckFileInput_Decrypt(self):
            if self.PathFileText.text() != "":
                self.DecryptFile()
            elif self.PathFileText.text() == "":
                pass

    def Encrypt(self):
        if self.IOtext.toPlainText() != "":
            if self.PassText.text() == "": 
                self.show_Error_Input_Empty()
            elif len(self.PassText.text().encode("utf-8")) > 16:
                self.show_Error_Long_Input()
            else:
                key = self.PassText.text().encode("utf-8")
                cipherText = main.Encrypt(self.IOtext.toPlainText(), key)
                self.IOtext.clear()
                cipherText = binascii.hexlify(cipherText)
                self.IOtext.setText(cipherText.decode("utf-8"))
        else:
            pass
    
    def DeCrypt(self):
        if self.IOtext.toPlainText() != "":
            if len(self.PassText.text().encode("utf-8")) > 16:
                self.show_Error_Long_Input()
            else:
                key = self.PassText.text().encode("utf-8")
                try:
                    cipherText = self.IOtext.toPlainText().encode("utf-8")
                    cipherText = binascii.unhexlify(cipherText)
                    plainText = main.Decrypt(cipherText, key)
                    self.IOtext.clear()
                    self.IOtext.setText(plainText)
                except:
                    self.show_Error_InputFile()
                    self.Clear()
        else:
            pass
    
    def EncryptFile(self):
        path_out = self.PathOutputText.text()
        key = self.PassText.text()
        if path_out == "":
            pass
        elif len(self.PassText.text().encode("utf-8")) > 16:
            self.show_Error_Long_Input()
        elif self.PassText.text() == "":
            self.show_Error_Input_Empty()
        else:
            try:
                str1 = list(self.PathFileText.text().split("*"))
                for i in str1:
                    main.EncryptFile(i, path_out, key)
            except:
                self.show_Error_InputFile()
                self.Clear()
    
    def DecryptFile(self):
        path_out = self.PathOutputText.text()
        key = self.PassText.text()
        if path_out == "":
            pass
        elif len(self.PassText.text().encode("utf-8")) > 16:
            self.show_Error_Long_Input()
        elif self.PassText.text() == "":
            self.show_Error_Input_Empty()
        else:
            try:
                str1 = list(self.PathFileText.text().split("*"))
                for i in str1:
                    main.DecryptFile(i, path_out, key)
            except:
                self.show_Error_InputFile()
                self.Clear()

    def EncryptRSA(self):
        try:
            if self.InputPlaintextRSA.toPlainText() == "" or self.InputKeyPath.text == "":
                pass
            else:
                plainText = self.InputPlaintextRSA.toPlainText()
                plainText = plainText.encode("utf-8")
                cipherText = main.EncryptRSA(self.InputKeyPath.text(), plainText)
                self.InputPlaintextRSA.clear()
                cipherText = binascii.hexlify(cipherText)
                cipherText = cipherText.decode("utf-8")
                self.InputPlaintextRSA.setText(cipherText)
        except:
            self.show_Error_InputFile()
            self.Clear()

    def DecryptRSA(self):
        if self.InputPlaintextRSA.toPlainText == "" or self.InputKeyPath.text == "":
            pass
        else:
            try:
                cipherText = self.InputPlaintextRSA.toPlainText()
                cipherText = cipherText.encode("utf-8")
                cipherText = binascii.unhexlify(cipherText)
                plainText = main.DecryptRSA(self.InputKeyPath.text(), cipherText)
                plainText = plainText.decode("utf-8")
                self.InputPlaintextRSA.clear()
                self.InputPlaintextRSA.setText(plainText)
            except:
                self.show_Error_InputFile()
                self.Clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AES & RSA Encryption"))
        self.label.setText(_translate("MainWindow", "Text:"))
        self.EncryptButton.setText(_translate("MainWindow", "Encrypt"))
        self.DecryptButton.setText(_translate("MainWindow", "Decrypt"))
        self.label_2.setText(_translate("MainWindow", "Nhập password:"))
        self.label_3.setText(_translate("MainWindow", "File:"))
        self.BrowseFileButton.setText(_translate("MainWindow", "Browse"))
        self.EncryptFileButton.setText(_translate("MainWindow", "Encrypt"))
        self.DecryptFileButton.setText(_translate("MainWindow", "Decrypt"))
        self.label_4.setText(_translate("MainWindow", "Output:"))
        self.BrowseOutputFileButton.setText(_translate("MainWindow", "Browse"))
        self.groupBox.setTitle(_translate("MainWindow", "AES"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.groupBox_2.setTitle(_translate("MainWindow", "RSA"))
        self.CreateKeyRSA.setText(_translate("MainWindow", "Tạo Key"))
        self.BrowseCreateKeyButton.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "Output:"))
        self.checkBoxXuatKey.setText(_translate("MainWindow", "Xuất Public Key"))
        self.label_6.setText(_translate("MainWindow", "Input Key:"))
        self.BrowseInputKeyRSA.setText(_translate("MainWindow", "Browse"))
        self.label_7.setText(_translate("MainWindow", "Thông tin cần mã hóa"))
        self.EncryptFileButton_2.setText(_translate("MainWindow", "Encrypt"))
        self.DecryptFileButton_2.setText(_translate("MainWindow", "Decrypt"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1024"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2048"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "4096"))

